jobs:
  linux-py36: &linux-template
    executor:
      name: python/default
      tag: "3.6.12"
    steps:
      - checkout
      - run:
          command: |
            pip install codecov
            pip install -r test_requirements
            pip install .
          name: Install
      - run:
          command: |
            python -m pytest --numpprocesses 'auto' --cov allensdk --cov-report xml
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
          name: Test
    
  linux-py37:
    <<: *linux-template
    executor:
      name: python/default
      tag: "3.7.7"

orbs:
  python: circleci/python@1.3.2
version: 2.1
workflows:
  main:
    jobs:
      - linux-py36
      - linux-py37
