version: 2
jobs:
  build:
    parallelism: 4
    environment:
      TEST_NWB_FILES: skip
      TEST_OBSERVATORY_EXPERIMENT_PLOTS_DATA: skip
      TEST_API_ENDPOINT: http://api.brain-map.org 
      TEST_COMPLETE: false
      TEST_BAMBOO: false
    branches:
      only:
        - master
        - /^rc\/.*/
        - /^feature\/.*/
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-package-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-package-dependencies-

      - run: 
          name: install package dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-package-dependencies-{{ checksum "requirements.txt" }}

      - run: 
          name: install test dependencies
          command: |
            . venv/bin/activate
            pip install -r test_requirements.txt
            pip install codecov
      
      # run tests
      - run: 
          name: run py36 job tests
          command: |
            sudo apt install rsync    # for copy utility tests
            . venv/bin/activate
            mkdir test-results
            TESTFILES=$(circleci tests glob test/**.py | circleci tests split --split-by=timings)
            echo ${TESTFILES}
            python3 -m pytest ${TESTFILES} --cov=allensdk --junitxml=test-results/junit.xml 
            codecov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1